"""Domain-specific algorithms for supply chain, fintech, accounting, and commerce."""

from agentic_algorithms.domains.accounting import (
    benford_anomaly_score,
    compute_trial_balance,
    post_journal_entry,
    reconcile_bank_transactions,
    validate_journal_entry,
)
from agentic_algorithms.domains.aeo import (
    aeo_page_score,
    citation_density_score,
    faq_structure_score,
    schema_completeness_score,
    snippet_answerability_score,
)
from agentic_algorithms.domains.ecommerce import (
    allocate_bandit_arm,
    din_attention_weights,
    epsilon_greedy_select,
    item_item_cf_scores,
    ndcg_at_k,
    recall_at_k,
    thompson_sampling_select,
    wide_deep_linear_score,
)
from agentic_algorithms.domains.expense import (
    categorize_expense,
    detect_duplicate_expenses,
    mileage_reimbursement,
    per_diem_check,
    policy_violation_score,
)
from agentic_algorithms.domains.fintech import (
    aml_structuring_score,
    amortization_schedule,
    compound_interest,
    luhn_check,
    payment_risk_score,
    simple_interest,
    velocity_check,
)
from agentic_algorithms.domains.geo import (
    delivery_zone_match,
    geohash_encode,
    haversine_km,
    jurisdiction_rate_lookup,
    nearest_facility,
    point_in_polygon,
)
from agentic_algorithms.domains.search import (
    SearchIndex,
    bm25_score,
    hybrid_search_rrf,
    tf_idf_vectorize,
)
from agentic_algorithms.domains.supply_chain import (
    allocate_inventory,
    atp_available,
    economic_order_quantity,
    exponential_smoothing_forecast,
    newsvendor_quantity,
    reorder_point,
    safety_stock,
    vehicle_route_nearest_neighbor,
)

__all__ = [
    "SearchIndex",
    "aeo_page_score",
    "allocate_bandit_arm",
    "allocate_inventory",
    "aml_structuring_score",
    "amortization_schedule",
    "atp_available",
    "benford_anomaly_score",
    "bm25_score",
    "categorize_expense",
    "citation_density_score",
    "compound_interest",
    "compute_trial_balance",
    "delivery_zone_match",
    "detect_duplicate_expenses",
    "din_attention_weights",
    "economic_order_quantity",
    "epsilon_greedy_select",
    "exponential_smoothing_forecast",
    "faq_structure_score",
    "geohash_encode",
    "haversine_km",
    "hybrid_search_rrf",
    "item_item_cf_scores",
    "jurisdiction_rate_lookup",
    "luhn_check",
    "mileage_reimbursement",
    "ndcg_at_k",
    "nearest_facility",
    "newsvendor_quantity",
    "payment_risk_score",
    "per_diem_check",
    "point_in_polygon",
    "policy_violation_score",
    "post_journal_entry",
    "recall_at_k",
    "reconcile_bank_transactions",
    "reorder_point",
    "safety_stock",
    "schema_completeness_score",
    "simple_interest",
    "snippet_answerability_score",
    "tf_idf_vectorize",
    "thompson_sampling_select",
    "validate_journal_entry",
    "vehicle_route_nearest_neighbor",
    "velocity_check",
    "wide_deep_linear_score",
]
