"""Data structures and algorithms reference implementations."""

from agentic_algorithms.dsa.arrays import (
    container_with_most_water,
    dutch_flag_sort,
    find_duplicate_floyd,
    insert_interval,
    longest_consecutive,
    majority_element_boyer_moore,
    max_subarray_circular,
    max_subarray_kadane,
    max_subarray_kadane_with_indices,
    merge_intervals,
    min_subarray_kadane,
    next_permutation,
    prefix_sum,
    product_except_self,
    range_sum,
    rotate_array,
    subarray_sum_equals_k,
    three_sum,
    trapping_rain_water,
    two_sum,
)
from agentic_algorithms.dsa.backtracking import (
    combination_sum,
    combinations,
    n_queens,
    permutations,
    subsets,
    sudoku_solver,
    word_search,
)
from agentic_algorithms.dsa.bits import (
    count_bits,
    power_of_two,
    single_number_xor,
    subsets_bitmask,
)
from agentic_algorithms.dsa.dp import (
    climb_stairs,
    coin_change,
    coin_change_ways,
    house_robber,
    house_robber_circular,
    knapsack_01,
    longest_increasing_subsequence_nlogn,
    matrix_chain,
    max_square,
    palindrome_partitioning_min_cuts,
    unbounded_knapsack,
)
from agentic_algorithms.dsa.graphs import (
    bellman_ford,
    bfs,
    build_adjacency_list,
    build_weighted_graph,
    course_schedule,
    detect_cycle_directed,
    detect_cycle_undirected,
    dfs,
    dijkstra,
    floyd_warshall,
    kruskal_mst,
    num_islands,
    prim_mst,
    topological_sort_dfs,
    topological_sort_kahn,
    word_ladder,
)
from agentic_algorithms.dsa.greedy import (
    activity_selection,
    gas_station,
    jump_game,
    partition_labels,
    task_scheduler,
)
from agentic_algorithms.dsa.heap import (
    MaxHeap,
    MedianFinder,
    MinHeap,
    kth_largest,
    merge_k_sorted_lists,
)
from agentic_algorithms.dsa.linked_lists import (
    ListNode,
    add_two_numbers,
    find_cycle_start,
    has_cycle_floyd,
    intersection_node,
    merge_two_lists,
    remove_nth_from_end,
    reorder_list,
    reverse_list,
)
from agentic_algorithms.dsa.math import (
    catalan,
    extended_gcd,
    factorial,
    fibonacci_fast_doubling,
    gcd,
    is_prime_miller_rabin,
    mod_pow,
    sieve_primes,
)
from agentic_algorithms.dsa.segments import SegmentTree
from agentic_algorithms.dsa.stacks_queues import (
    MinStack,
    daily_temperatures,
    evaluate_rpn,
    largest_rectangle_histogram,
    sliding_window_max,
)
from agentic_algorithms.dsa.sorting import (
    binary_search,
    counting_sort,
    first_position,
    heap_sort,
    last_position,
    lower_bound,
    merge_sort,
    quick_sort,
    radix_sort,
    search_rotated_array,
    upper_bound,
)
from agentic_algorithms.dsa.strings import (
    edit_distance_levenshtein,
    group_anagrams,
    is_palindrome,
    isomorphic_strings,
    kmp_search,
    longest_common_prefix,
    longest_common_subsequence,
    longest_palindrome_expand,
    min_window_substring,
    rabin_karp,
    regex_wildcard_dp,
    valid_parentheses,
)
from agentic_algorithms.dsa.trees import (
    TreeNode,
    build_from_preorder_inorder,
    deserialize,
    diameter,
    inorder_iterative,
    inorder_recursive,
    is_valid_bst,
    level_order,
    lowest_common_ancestor,
    max_depth,
    path_sum,
    postorder_iterative,
    postorder_recursive,
    preorder_iterative,
    preorder_recursive,
    serialize,
)
from agentic_algorithms.dsa.trie import Trie, TrieNode, word_search_ii
from agentic_algorithms.dsa.union_find import UnionFind

__all__ = [
  # arrays
    "container_with_most_water",
    "dutch_flag_sort",
    "find_duplicate_floyd",
    "insert_interval",
    "longest_consecutive",
    "majority_element_boyer_moore",
    "max_subarray_circular",
    "max_subarray_kadane",
    "max_subarray_kadane_with_indices",
    "merge_intervals",
    "min_subarray_kadane",
    "next_permutation",
    "prefix_sum",
    "product_except_self",
    "range_sum",
    "rotate_array",
    "subarray_sum_equals_k",
    "three_sum",
    "trapping_rain_water",
    "two_sum",
    # backtracking
    "combination_sum",
    "combinations",
    "n_queens",
    "permutations",
    "subsets",
    "sudoku_solver",
    "word_search",
    # bits
    "count_bits",
    "power_of_two",
    "single_number_xor",
    "subsets_bitmask",
    # dp
    "climb_stairs",
    "coin_change",
    "coin_change_ways",
    "house_robber",
    "house_robber_circular",
    "knapsack_01",
    "longest_increasing_subsequence_nlogn",
    "matrix_chain",
    "max_square",
    "palindrome_partitioning_min_cuts",
    "unbounded_knapsack",
    # graphs
    "bellman_ford",
    "bfs",
    "build_adjacency_list",
    "build_weighted_graph",
    "course_schedule",
    "detect_cycle_directed",
    "detect_cycle_undirected",
    "dfs",
    "dijkstra",
    "floyd_warshall",
    "kruskal_mst",
    "num_islands",
    "prim_mst",
    "topological_sort_dfs",
    "topological_sort_kahn",
    "word_ladder",
    # greedy
    "activity_selection",
    "gas_station",
    "jump_game",
    "partition_labels",
    "task_scheduler",
    # heap
    "MaxHeap",
    "MedianFinder",
    "MinHeap",
    "kth_largest",
    "merge_k_sorted_lists",
    # linked lists
    "ListNode",
    "add_two_numbers",
    "find_cycle_start",
    "has_cycle_floyd",
    "intersection_node",
    "merge_two_lists",
    "remove_nth_from_end",
    "reorder_list",
    "reverse_list",
    # math
    "catalan",
    "extended_gcd",
    "factorial",
    "fibonacci_fast_doubling",
    "gcd",
    "is_prime_miller_rabin",
    "mod_pow",
    "sieve_primes",
    # segments
    "SegmentTree",
    # stacks_queues
    "MinStack",
    "daily_temperatures",
    "evaluate_rpn",
    "largest_rectangle_histogram",
    "sliding_window_max",
    # sorting
    "binary_search",
    "counting_sort",
    "first_position",
    "heap_sort",
    "last_position",
    "lower_bound",
    "merge_sort",
    "quick_sort",
    "radix_sort",
    "search_rotated_array",
    "upper_bound",
    # strings
    "edit_distance_levenshtein",
    "group_anagrams",
    "is_palindrome",
    "isomorphic_strings",
    "kmp_search",
    "longest_common_prefix",
    "longest_common_subsequence",
    "longest_palindrome_expand",
    "min_window_substring",
    "rabin_karp",
    "regex_wildcard_dp",
    "valid_parentheses",
    # trees
    "TreeNode",
    "build_from_preorder_inorder",
    "deserialize",
    "diameter",
    "inorder_iterative",
    "inorder_recursive",
    "is_valid_bst",
    "level_order",
    "lowest_common_ancestor",
    "max_depth",
    "path_sum",
    "postorder_iterative",
    "postorder_recursive",
    "preorder_iterative",
    "preorder_recursive",
    "serialize",
    # trie
    "Trie",
    "TrieNode",
    "word_search_ii",
    # union find
    "UnionFind",
]
